# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import setmis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternate_Id_Type_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen_Resident_Status_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Communicating_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_registration_number', models.CharField(max_length=20)),
                ('designation_etqe_id', models.CharField(max_length=10)),
                ('designation_start_date', models.DateField()),
                ('designation_end_date', models.DateField(blank=True)),
                ('etqe_decision_number', models.CharField(blank=True, max_length=20)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Designation_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Designation_Structure_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Economic_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdl_no', models.CharField(max_length=10)),
                ('site_no', models.CharField(max_length=10)),
                ('employer_registration_number', models.CharField(blank=True, max_length=20)),
                ('employer_company_name', models.CharField(max_length=70)),
                ('employer_trading_name', models.CharField(max_length=70)),
                ('employer_postal_address_1', models.CharField(max_length=50)),
                ('employer_postal_address_2', models.CharField(max_length=50)),
                ('employer_postal_address_3', models.CharField(blank=True, max_length=50)),
                ('employer_postal_address_code', models.CharField(max_length=4)),
                ('employer_physical_address_1', models.CharField(max_length=50)),
                ('employer_physical_address_2', models.CharField(max_length=50)),
                ('employer_physical_address_3', models.CharField(blank=True, max_length=50)),
                ('employer_physical_address_code', models.CharField(max_length=4)),
                ('employer_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('employer_fax_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('employer_contact_name', models.CharField(blank=True, max_length=20)),
                ('employer_contact_email_address', models.EmailField(blank=True, max_length=50)),
                ('employer_contact_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('employer_contact_cell_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('employer_approval_status_id', models.CharField(blank=True, max_length=10)),
                ('employer_approval_start_date', models.DateField()),
                ('employer_approval_end_date', models.DateField()),
                ('employer_approval_status_num', models.CharField(blank=True, max_length=20)),
                ('latitude_degree', models.CharField(blank=True, max_length=3)),
                ('latitude_minutes', models.CharField(blank=True, max_length=2)),
                ('latitude_seconds', models.CharField(blank=True, max_length=6)),
                ('longitude_degree', models.CharField(blank=True, max_length=2)),
                ('longitude_minutes', models.CharField(blank=True, max_length=2)),
                ('longitude_seconds', models.CharField(blank=True, max_length=6)),
                ('main_sdl_no', models.CharField(max_length=10)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Country_Code', to_field='lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_Approval_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment_Status_Reason_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment_Type_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Equity_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funding_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gender_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hearing_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Language_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.CharField(max_length=10)),
                ('qualification_achievement_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cumulative_spend', models.CharField(max_length=10)),
                ('date_stamp', models.DateField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Employer')),
                ('enrolment_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Status_Id', to_field='lookup')),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Funding_Id', to_field='lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Learnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnership_id', models.CharField(max_length=10)),
                ('assessor_registration_number', models.CharField(blank=True, max_length=20)),
                ('enrolment_status_date', models.DateField()),
                ('enrolment_date', models.DateField()),
                ('assessor_etqe_id', models.CharField(blank=True, max_length=10)),
                ('most_recent_registration_date', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=30)),
                ('cumulative_spend', models.CharField(blank=True, max_length=10)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('economic_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Economic_Status_Id', to_field='lookup')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Employer')),
                ('enrolment_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Status_Id', to_field='lookup')),
                ('enrolment_status_reason_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Status_Reason_Id', to_field='lookup')),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Funding_Id', to_field='lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Learnership_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Technical', 'Technical'), ('Academic', 'Academic')], max_length=1)),
                ('date_stamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Non_NQF_Interv_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OFO_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Part_Of_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=15, validators=[setmis.models.validateID])),
                ('person_alternate_id', models.CharField(blank=True, max_length=20)),
                ('person_last_name', models.CharField(max_length=45, validators=[setmis.models.validate_na_geen, setmis.models.validate_names])),
                ('person_first_name', models.CharField(max_length=26, validators=[setmis.models.validate_na_geen, setmis.models.validate_names])),
                ('person_middle_name', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_names])),
                ('person_title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10)),
                ('person_birth_date', models.DateField(max_length=8, validators=[setmis.models.validate_sixteen, setmis.models.validate_eighteen_fifty])),
                ('person_postal_address_1', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_postal_address_2', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_postal_address_3', models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_postal_address_code', models.CharField(max_length=4)),
                ('person_home_address_1', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_home_address_2', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_home_address_3', models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('person_address_code', models.CharField(max_length=4)),
                ('person_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('person_cell_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('person_fax_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('person_email_address', models.EmailField(blank=True, max_length=50)),
                ('person_previous_last_name', models.CharField(blank=True, max_length=45)),
                ('person_previous_alternate_id', models.CharField(blank=True, max_length=20)),
                ('person_previous_alternate_id_type_id', models.CharField(blank=True, max_length=3)),
                ('person_previous_provider_code', models.CharField(blank=True, max_length=20)),
                ('person_previous_provider_etqe_id', models.CharField(blank=True, max_length=10)),
                ('last_school_emis_number', models.CharField(blank=True, max_length=10, null=True)),
                ('last_school_year', models.CharField(blank=True, max_length=4, null=True)),
                ('popi_act_status_date', models.DateField(blank=True, null=True)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('alternate_id_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Alternate_Id_Type_Id', to_field='lookup')),
                ('citizen_resident_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Citizen_Resident_Status_Code', to_field='lookup')),
                ('communicating_rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Communicating_Rating_Id', to_field='lookup')),
                ('equity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Equity_Code', to_field='lookup')),
                ('gender_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Gender_Code', to_field='lookup')),
                ('hearing_rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Hearing_Rating_Id', to_field='lookup')),
                ('home_language_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Home_Language_Code', to_field='lookup')),
                ('nationality_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Nationality_Code', to_field='lookup')),
            ],
        ),
        migrations.CreateModel(
            name='POPI_Act_Status_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=20, validators=[setmis.models.validate_uppercase_letters_numbers_special])),
                ('provider_etqe_id', models.CharField(max_length=10)),
                ('provider_name', models.CharField(max_length=70, validators=[setmis.models.validate_na_geen])),
                ('provider_postal_address_1', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('provider_postal_address_2', models.CharField(max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('provider_postal_address_3', models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special])),
                ('provider_postal_address_code', models.CharField(max_length=4, validators=[setmis.models.validate_postcode])),
                ('provider_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('provider_fax_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('provider_sars_number', models.CharField(blank=True, max_length=20)),
                ('provider_contact_name', models.CharField(blank=True, max_length=20)),
                ('provider_contact_email_address', models.EmailField(blank=True, max_length=50)),
                ('provider_contact_phone_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('provider_contact_cell_number', models.CharField(blank=True, max_length=20, validators=[setmis.models.validate_phone_fax])),
                ('provider_accreditation_num', models.CharField(blank=True, max_length=20)),
                ('provider_start_date', models.DateField()),
                ('provider_end_date', models.DateField(blank=True, null=True)),
                ('etqe_decision_number', models.CharField(blank=True, max_length=20)),
                ('provider_class_id', models.CharField(max_length=10)),
                ('provider_status_id', models.CharField(max_length=10)),
                ('latitude_degree', models.CharField(blank=True, max_length=3)),
                ('latitude_minutes', models.CharField(blank=True, max_length=2)),
                ('latitude_seconds', models.CharField(blank=True, max_length=6)),
                ('longitude_degree', models.CharField(blank=True, max_length=2)),
                ('longitude_minutes', models.CharField(blank=True, max_length=2)),
                ('longitude_seconds', models.CharField(blank=True, max_length=6)),
                ('provider_physical_address_1', models.CharField(max_length=50)),
                ('provider_physical_address_2', models.CharField(max_length=50)),
                ('provider_physical_address_3', models.CharField(blank=True, max_length=50)),
                ('provider_physical_address_code', models.CharField(max_length=4)),
                ('provider_website_address', models.URLField(blank=True)),
                ('sdl_no', models.CharField(blank=True, max_length=10)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Country_Code', to_field='lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Provider_class_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provider_Status_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provider_Type_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Province_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.CharField(max_length=10)),
                ('assessor_registration_number', models.CharField(blank=True, max_length=20)),
                ('part_of_id', models.CharField(max_length=2)),
                ('assessor_etqe_id', models.CharField(blank=True, max_length=20)),
                ('enrolment_status_reason_id', models.CharField(blank=True, max_length=10)),
                ('most_recent_registration_date', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=30)),
                ('economic_status_id', models.CharField(max_length=10)),
                ('practical_provider', models.CharField(blank=True, max_length=20)),
                ('practical_etqe_id', models.CharField(blank=True, max_length=10)),
                ('funding_id', models.CharField(max_length=10)),
                ('cumulative_spend', models.CharField(blank=True, max_length=10)),
                ('ofo_code', models.CharField(blank=True, max_length=15)),
                ('urban_rural_id', models.CharField(max_length=3)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Employer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Person')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Remembering_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Seeing_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Self_Care_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SETA_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SIC_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='STATSSA_Area_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subfield_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_Test_Result_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_Test_Result_Reason_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_standard_id', models.CharField(max_length=10)),
                ('assessor_registration_number', models.CharField(blank=True, max_length=20)),
                ('enrolment_status_date', models.DateField()),
                ('enrolment_date', models.DateField()),
                ('part_of_id', models.CharField(max_length=2)),
                ('qualification_id', models.CharField(blank=True, max_length=10)),
                ('learnership_id', models.CharField(blank=True, max_length=10)),
                ('assessor_etqe_id', models.CharField(blank=True, max_length=20)),
                ('most_recent_registration_date', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=30)),
                ('non_nqf_interv_provider', models.CharField(blank=True, max_length=20)),
                ('non_nqf_interv_etqe_id', models.CharField(blank=True, max_length=10)),
                ('cumulative_spend', models.CharField(blank=True, max_length=10)),
                ('date_stamp', models.DateField(default=datetime.datetime.now)),
                ('economic_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Economic_Status_Id', to_field='lookup')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Employer')),
                ('enrolment_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Status_Id', to_field='lookup')),
                ('enrolment_status_reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Status_Reason_Id', to_field='lookup')),
                ('enrolment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Enrolment_Type_Id', to_field='lookup')),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Funding_Id', to_field='lookup')),
                ('ofo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.OFO_Code', to_field='lookup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Person')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Urban_Rural_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Walking_Rating_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='unit_standard',
            name='urban_rural_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Urban_Rural_ID', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider_Type_Id'),
        ),
        migrations.AddField(
            model_name='provider',
            name='province_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Province_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='provider',
            name='sic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.SIC_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='popi_act_status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.POPI_Act_Status_ID', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='provider_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider'),
        ),
        migrations.AddField(
            model_name='person',
            name='province_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Province_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='remembering_rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Remembering_Rating_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='seeing_rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Seeing_Rating_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='self_care_rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Self_Care_Rating_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='statssa_area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.STATSSA_Area_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='person',
            name='walking_rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.Walking_Rating_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='learnership',
            name='learnership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Learnership_Type'),
        ),
        migrations.AddField(
            model_name='learnership',
            name='ofo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.OFO_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='learnership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Person'),
        ),
        migrations.AddField(
            model_name='learnership',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider'),
        ),
        migrations.AddField(
            model_name='learnership',
            name='urban_rural_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Urban_Rural_ID', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='internship_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Internship_Status_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='ofo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.OFO_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Person'),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='provider_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider'),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='urban_rural_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Urban_Rural_ID', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='employer',
            name='province_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Province_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='employer',
            name='seta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.SETA_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='employer',
            name='sic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setmis.SIC_Code', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Designation_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_structure_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Designation_Structure_Status_Id', to_field='lookup'),
        ),
        migrations.AddField(
            model_name='designation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Person'),
        ),
        migrations.AddField(
            model_name='designation',
            name='provider_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Provider'),
        ),
    ]
