# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='learnership_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Academic', 'Academic')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Learnership_Type',
        ),
    ]
