# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0002_auto_20180116_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_NQF_Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_nqf_intervention_code', models.CharField(max_length=10)),
                ('non_nqf_intervention_name', models.CharField(max_length=10)),
                ('non_nqf_registration_start_date', models.DateField()),
                ('non_nqf_registration_end_date', models.DateField()),
                ('non_nqf_intervention_etqe_id', models.CharField(max_length=10)),
                ('non_nqf_credit', models.CharField(max_length=10)),
                ('date_stamp', models.DateField()),
                ('non_nqf_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Non_NQF_Interv_Status_Id', to_field='lookup')),
                ('subfield_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Subfield_Id', to_field='lookup')),
            ],
        ),
    ]
