# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0003_non_nqf_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_nqf_intervention',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setmis.Person'),
            preserve_default=False,
        ),
    ]
