# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import setmis.models


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0006_person_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_postal_address_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_postal_address_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_postal_address_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='learnership',
            name='learnership_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Academic', 'Academic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_postal_address_1',
            field=models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special]),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_postal_address_2',
            field=models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special]),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_postal_address_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_postal_address_1',
            field=models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_postal_address_2',
            field=models.CharField(blank=True, max_length=50, validators=[setmis.models.validate_na_geen, setmis.models.validate_letters_special]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_postal_address_code',
            field=models.CharField(blank=True, max_length=4, validators=[setmis.models.validate_postcode]),
        ),
    ]
