# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0008_auto_20180201_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='learnership_id',
            field=models.CharField(choices=[('436', '436 - Certificate in General Nursing (Enrolled) Level 4'), ('437', '437 - Diploma in General Nursing (Bridging) Level 5'), ('440', '440 - Certificate in General Nursing (Auxiliary) Level 4'), ('442', '442 - Post Basic Diploma in Medical/Surgical Nursing (Elective: Critical Care/Operating Theater Nursing) Level 6'), ('444', '444 - FET Certificate in Social Auxiliary Work Level 4'), ('446', '446 - Further Education and Training Certificate: Child and Youth Care Work Level 4'), ('1117', '1117 - National Certificate: Pharmacist Assistance Level 3'), ('1118', '1118 - Ferther Education and Training Certificate: Pharmacist Assistance Level 4'), ('1357', '1357 - Further Education and Training Certificate:  Early Childhood Development Level 4'), ('268', '268 - L5 - Learnership for ECD Trainers Level 5')], max_length=10),
        ),
    ]
