# Generated by Django 2.0.6 on 2018-07-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0009_auto_20180201_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='learning_programme_type_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='economic_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Economic_Status_Id', to_field='lookup'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='funding_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Funding_Id', to_field='lookup'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='ofo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.OFO_Code', to_field='lookup'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='part_of_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Part_Of_Id', to_field='lookup'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='urban_rural_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setmis.Urban_Rural_ID', to_field='lookup'),
        ),
    ]
