# Generated by Django 2.0.6 on 2018-08-21 08:55

from django.db import migrations, models
import setmis.models


class Migration(migrations.Migration):

    dependencies = [
        ('setmis', '0010_auto_20180713_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='learnership_id',
            field=models.CharField(choices=[('436', '436 - Certificate in General Nursing (Enrolled) Level 4'), ('437', '437 - Diploma in General Nursing (Bridging) Level 5'), ('439', '439 - FETC Phlebotomy Techniques NQF Level 4'), ('440', '440 - Certificate in General Nursing (Auxiliary) Level 4'), ('442', '442 - Post Basic Diploma in Medical/Surgical Nursing (Elective: Critical Care/Operating Theater Nursing) Level 6'), ('444', '444 - FET Certificate in Social Auxiliary Work Level 4'), ('446', '446 - Further Education and Training Certificate: Child and Youth Care Work Level 4'), ('448', '448 - Health Promotion Officer NQF Level 3'), ('1117', '1117 - National Certificate: Pharmacist Assistance Level 3'), ('1118', '1118 - Ferther Education and Training Certificate: Pharmacist Assistance Level 4'), ('1357', '1357 - Further Education and Training Certificate:  Early Childhood Development Level 4'), ('268', '268 - L5 - Learnership for ECD Trainers Level 5'), ('6591', '6591 - University Diploma:Veterinary Nursing Level 6'), ('10809', '10809 - Post Basic Diploma: Operating  Theater Nursing Science Level 7'), ('21214', '21214 - Post Basic Diploma: Medical and Surgical Nursing Science Level 7'), ('16496', '16496 - Advance University Diploma: Midwifery and Neonatal Nursing Level 7'), ('17196', '17196 - Bridging Diploma: Nursing General Level 5'), ('97756', '97756 - Higher Certificate: Auxilliary Nursing Level 5'), ('72049', '72049 - National Certificate: Pharmacy Assistant Level 3'), ('72050', '72050 - Further Education and training Certificate: Pharmacy Assistant Level 4'), ('59345', '59345 - Further Education and training Certificate: Phlebotomy Technique Level 4'), ('60209', '60209 - Further Education and training Certificate: Child & Youthcare Level 4'), ('94597', '94597 - Occupational Certificate: Health Promotion Officer Level 3'), ('99510', '99510 - Occupational Certificate: Child and Youth care Worker Level 5'), ('98890', '98890 - Occupational Certificate: Social Auxiliary Worker Level 5'), ('1502', '1502 - National Certificate: Occupational Health, Safety and Environment: Mining and Minerals, Level 2'), ('1111', '1111 - General Education and Training Certificate: Business Practice, Level 1'), ('1216', '1216 - National Certificate: Public Administration: Leadership, Level 5'), ('1217', '1217 - National Certificate: Public Administration: Procurement, Level 5'), ('797', '797 - Office Administration Assistant, Level 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(blank=True, max_length=15, validators=[setmis.models.validateID]),
        ),
    ]
